# This file describes a conda environment that can be to install jwql
#
# Run the following command to set up this environment:
# $ conda env create -f environment_python_3_8.yml
#
# The environment name can be overridden with the following command:
# $ conda env create -n <custom name> -f environment_python_3_8.yml
#
# Run the following command to activate the environment:
# $ source activate jwql-3.8
#
# To deactivate the environment run the following command:
# $ source deactivate
#
# To remove the environment entirely, run the following command:
# $ conda env remove -n jwql-3.8

name: jwql-3.8

channels:
  - conda-forge
  - defaults

dependencies:
  - astropy=5.2.1
  - bokeh=2.4.3
  - beautifulsoup4=4.11.2
  - celery=5.2.7
  - codecov=2.1.12
  - cryptography=39.0.1
  - django=4.1.7
  - flake8=6.0.0
  - inflection=0.5.1
  - ipython=8.10.0
  - jinja2=3.1.2
  - jsonschema=4.17.3
  - matplotlib=3.7.0
  - nodejs=18.12.1
  - numpy=1.24.2
  - numpydoc=1.5.0
  - pip=23.0
  - postgresql=15.2
  - psycopg2=2.9.3
  - pytest=7.2.1
  - pytest-cov=4.0.0
  - pytest-mock=3.10.0
  - python=3.8.16
  - pyyaml=6.0
  - redis
  - scipy=1.9.3
  - setuptools=67.3.1
  - sphinx=6.1.3
  - sphinx_rtd_theme=1.2.0
  - sqlalchemy=2.0.8
  - twine=4.0.2
  - wtforms=3.0.1

  - pip:
    - astroquery==0.4.6
    - bandit==1.7.4
    - jwst==1.10.0
    - pandas=2.0.0
    - pysiaf==0.19.1
    - pysqlite3==0.5.0
    - pyvo==1.4
    - redis==4.5.1
    - selenium==4.8.0
    - stdatamodels==0.4.5
    - stsci_rtd_theme==1.0.0
    - vine==5.0.0
    - git+https://github.com/spacetelescope/jwst_reffiles

    # Current package
    - -e .
