# This file describes a conda environment that can be to install jwql
#
# Run the following command to set up this environment:
# $ conda env create -f environment_python_3_8.yml
#
# The environment name can be overridden with the following command:
# $ conda env create -n <custom name> -f environment_python_3_8.yml
#
# Run the following command to activate the environment:
# $ source activate jwql-3.8
#
# To deactivate the environment run the following command:
# $ source deactivate
#
# To remove the environment entirely, run the following command:
# $ conda env remove -n jwql-3.8

name: jwql-3.8

channels:
  - defaults

dependencies:
  - astropy=5.0.2
  - bokeh=2.4.2
  - beautifulsoup4=4.10.0
  - 
  - codecov=2.1.11
  - cryptography=36.0.0
  - django=3.2.5
  - flake8=3.9.2
  - inflection=0.5.1
  - ipython=7.29.0
  - jinja2=3.0.2
  - jsonschema=3.2.0
  - matplotlib=3.4.2
  - nodejs=10.13.0
  - numpy=1.20.3
  - numpydoc=1.1.0
  - pandas=1.3.4
  - pip=21.0.1
  - postgresql=12.2
  - psycopg2=2.8.6
  - pytest=6.2.4
  - pytest-cov=3.0.0
  - python=3.8.5
  - pyyaml=5.4.1
  - scipy=1.7.1
  - setuptools=52.0.0
  - sphinx=4.2.0
  - sphinx_rtd_theme=0.4.3
  - sqlalchemy=1.4.27
  - twine=3.4.1
  - wtforms=2.3.3

  - pip:
    - asdf==2.11.0
    - astroquery==0.4.5
    - bandit==1.7.4
    - celery\[redis\]==5.2.3
    - celery-singleton==0.3.1
    - crds==11.10.0
    - jwst==1.3.3
    - pysiaf==0.11.0
    - pysqlite3==0.4.3
    - stdatamodels==0.2.4
    - stsci_rtd_theme==0.0.2
    - git+https://github.com/spacetelescope/jwst_reffiles
    
    # Current package
    - -e .
