# This file describes a conda environment that can be to install jwql
#
# Run the following command to set up this environment:
# $ conda env create -f environment_python_3_8.yml
#
# The environment name can be overridden with the following command:
# $ conda env create -n <custom name> -f environment_python_3_8.yml
#
# Run the following command to activate the environment:
# $ source activate jwql-3.8
#
# To deactivate the environment run the following command:
# $ source deactivate
#
# To remove the environment entirely, run the following command:
# $ conda env remove -n jwql-3.8

name: jwql-3.8

channels:
  - defaults

dependencies:
  - astropy=5.1
  - bokeh=2.4.3
  - beautifulsoup4=4.11.1
  - celery=5.0.5
  - codecov=2.1.11
  - cryptography=38.0.1
  - django=4.1
  - flake8=4.0.1
  - inflection=0.5.1
  - ipython=8.4.0
  - jinja2=3.1.2
  - jsonschema=4.16.0
  - matplotlib=3.5.3
  - nodejs=10.13.0
  - numpy=1.21.5
  - numpydoc=1.4.0
  - pandas=1.4.4
  - pip=22.2.2
  - postgresql=12.2
  - psycopg2=2.8.6
  - pytest=7.1.2
  - pytest-cov=3.0.0
  - python=3.8.13
  - pyyaml=6.0
  - redis
  - scipy=1.9.1
  - setuptools=65.5.0
  - sphinx=5.0.2
  - sphinx_rtd_theme=0.4.3
  - sqlalchemy=1.4.39
  - twine=3.7.1
  - wtforms=2.3.3

  - pip:
    - astroquery==0.4.6
    - bandit==1.7.4
    - jwst==1.8.2
    - pysiaf==0.18.0
    - pysqlite3==0.4.7
    - pyvo==1.4
    - redis
    - stsci_rtd_theme==1.0.0
    - stcal==1.2.1
    - git+https://github.com/spacetelescope/jwst_reffiles

    # Current package
    - -e .
