channels:
- http://ssb.stsci.edu/astroconda-dev
- defaults
dependencies:
- asdf=2.3.0
- astropy>=3.1.2
- astroquery=0.3.9
- bokeh=0.13.0
- crds>=7.2.7
- django=2.1.1
- ipython=6.5.0
- jinja2=2.10
- jwst=0.13.0
- matplotlib=3.0.0
- numpy=1.15.2
- numpydoc=0.8.0
- pandas=0.23.4
- postgresql=9.6.6
- psycopg2=2.7.5
- python=3.5.6
- python-dateutil=2.7.3
- pytest=3.8.1
- pytest-cov=2.6.0
- pytest-html=1.19.0
- sphinx=2.0.1
- sphinx_rtd_theme=0.1.9
- sqlalchemy=1.2.11
- stsci_rtd_theme=0.0.2
- twine=1.13.0
- pip:
  - authlib==0.10
  - codecov==2.0.15
  - jwedb>=0.0.3
  - pysiaf==0.2.5
  - sphinx-automodapi==0.10
