channels:
- defaults
- http://ssb.stsci.edu/astroconda
dependencies:
- astroquery=0.4
- bokeh=2.1.1
- django=3.0.3
- flake8=3.8.3
- inflection=0.3.1
- ipython=7.16.1
- jinja2=2.11.2
- jsonschema=3.2.0
- matplotlib=3.2.2
- nodejs=10.13.0
- numpy=1.18.5
- numpydoc=1.1.0
- pandas=1.0.5
- pip=20.1.1
- postgresql=12.2
- psycopg2=2.8.5
- pysiaf=0.9.0
- python=3.7.8
- pytest=5.4.3
- pytest-cov=2.10.0
- scipy=1.5.0
- setuptools=49.2.0
- sphinx=3.1.2
- sqlalchemy=1.3.18
- twine=2.0.0
- pip:
  - asdf==2.7.0
  - astropy==4.0.1.post1
  - authlib==0.14.3
  - codecov==2.1.8
  - crds==7.5.0.0
  - jwedb==0.0.6
  - pysqlite3==0.4.3
  - stsci_rtd_theme==0.0.2
  - git+https://github.com/spacetelescope/jwst@0.16.2
  - git+https://github.com/spacetelescope/jwst_reffiles
