name: jwqldev
channels:
- defaults
- http://ssb.stsci.edu/astroconda-dev
dependencies:
- astropy=3.0
- django=1.11.8
- jwst=0.7.8rc9
- matplotlib=2.1.1
- numpy=1.14.0
- numpydoc=0.8.0
- postgresql=9.6.6
- python=3.6.4
- python-dateutil=2.6.1
- sphinx=1.6.6
- sphinx_rtd_theme=0.1.9
- sqlalchemy=1.2.0
- stsci_rtd_theme=0.0.1
- pip:
  - sphinx-automodapi==0.7