name: jwql
channels:
- http://ssb.stsci.edu/astroconda-dev
- defaults
dependencies:
- asdf>=2.3.0
- astropy
- astroquery=0.3.9
- bokeh=1.0.4
- django=2.1.5
- ipython=7.3.0
- jinja2=2.10
- jwst
- matplotlib=3.0.2
- numpy=1.16.2
- numpydoc=0.8.0
- pandas=0.24.0
- postgresql=9.6.6
- psycopg2=2.7.5
- python=3.6.4
- python-dateutil=2.7.5
- pytest=4.3.0
- pytest-cov=2.6.1
- pytest-html=1.19.0
- sphinx=1.8.5
- sphinx_rtd_theme=0.1.9
- sqlalchemy=1.3.1
- stsci_rtd_theme=0.0.2
- pip:
  - authlib==0.10
  - sphinx-automodapi==0.10
