name: jwql
channels:
- defaults
- http://ssb.stsci.edu/astroconda-dev
dependencies:
- python=3.6
- astropy=3.0
- astroquery=0.3.8
- bokeh=0.12.5
- django=2.0.5
- ipython=6.4.0
- jinja2=2.10
- jwst=0.7.8rc9
- matplotlib=2.1.1
- numpy=1.14.0
- numpydoc=0.8.0
- postgresql=9.6.6
- psycopg2=2.7.5
- python=3.6.4
- python-dateutil=2.6.1
- pytest=3.4.2
- sphinx=1.6.6
- sphinx_rtd_theme=0.1.9
- sqlalchemy=1.2.0
- stsci_rtd_theme=0.0.1
- pip:
  - sphinx-automodapi==0.7
